### ISSUE TITLE
Invalid video appearing in search results

### ISSUE THREAD

**Issue by MindfulMinun** [talmobi/yt-search#3]
When performing a search, occasionally a video appears at the top of the results that’s invalid. Its `videoId` field isn’t a valid video ID, the `ago` property lists views, and the `views`, `duration`, and `seconds` properties are zeroed.

Here I searched for "test" a few times and this video was prepended to the results. (Notice how there are 21 elements in the array instead of 20.)

![](https://user-images.githubusercontent.com/15158256/71388474-2439c080-25be-11ea-823b-5407bfd25602.png)

Unfortunately, I can't find a way to reliably reproduce the error, it only happens occasionally. 

My current work-around is to filter the results for the weird ID (which seems to be invariant).
```js
ytSearch({
    query: searchQuery,
    pageStart: searchPage,
    pageEnd: searchPage + 1
}, function(err, results) {
    results = results.filter(r => r.videoId !== 'L&ai')
    // Rest of code
})
```

**Comment by talmobi** [comment]
Hello,

Thanks for the informative report. I managed to reproduce the error quite consistently by simply using the search term "mobile test automation".

The problem was that sometimes ads would be added to the page at the top and the parsing of those links were not taken into consideration.

I published a fix as npm version 0.4.3, the commit is here: https://github.com/talmobi/yt-search/commit/4d9266d5b7d236c38fd352d3c2af38ae4eb5cdb7

`npm install yt-search@latest`
`npm install yt-search@0.4.3`

If you can please test this new version and check if it fixes your issue, thank you.

**Comment by AzSa5z1n** [comment]
I am still getting "L&ai" in the results when using 'yt-search YouTube Premium ()' quite consistently. After the update.
![image](https://user-images.githubusercontent.com/26307955/71840672-c44a1c00-308b-11ea-9dc3-f307e6baa80a.png)

**Comment by talmobi** [comment]
Hello, it seems like you installed the latest `yt-search` module locally, but then are using the globally installed `yt-search` cli. Can you try installing it globally and try the same command again?

`npm install -g yt-serch@latest`

or alternatively try with the local version that you installed:

`./node_modules/.bin/yt-search`

Currently I don't seem to be to be able to reproduce the error.

**Comment by AzSa5z1n** [comment]
Sorry, you were correct uninstalling my global version fixed the issues I was having. Thank you!

**Comment by talmobi** [comment]
@AzSa5z1n

Thank you for the detailed report, testing and responses! (:
